# Generated by Django 5.0.6 on 2024-06-26 07:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_head_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('dateBuy', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='receiptDetails',
            fields=[
                ('receipt_id_Details', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('receipt_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.receipt')),
            ],
        ),
    ]
