# Generated by Django 5.0.6 on 2024-07-15 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptdetails',
            name='receipt_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.receipt'),
        ),
    ]
